server:
  port: 8082

spring:
  application:
    name: fraud
  datasource:
    username: porunit
    url: jdbc:postgresql://postgres:5432/fraud
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  zipkin:
    base-url: http://zipkin:9411


